import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Fotoverifier 2.0',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen w-screen flex">{children}</body>
    </html>
  );
}
