services:
  redis:
    image: "redis:latest"
    container_name: redis
  
  uvicorn:
    # build: ./Backend_new
    # If you want to use a local tag instead of building:
    image: letahoangchuong/fotoverifier-backend:latest
    container_name: fotoverifier-backend
    ports:
      - "9001:9001"
    command: uvicorn main:app --host 0.0.0.0 --port 9001
    env_file:
      - ./Backend_new/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - FRONTEND_URL=http://next:9002
    depends_on:
      - redis

  celery:
    # build: ./Backend_new
    # If you want to use a local tag instead of building:
    image: letahoangchuong/fotoverifier-backend:latest
    container_name: celery-worker
    command: celery -A tasks worker --loglevel=info --concurrency=3
    env_file:
      - ./Backend_new/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - FRONTEND_URL=http://next:9002
    depends_on:
      - redis
      - uvicorn

  next:
    # build: ./Frontend
    # If you want to use a local tag instead of building:
    image: letahoangchuong/fotoverifier-frontend:latest
    container_name: fotoverifier-frontend
    ports:
      - "9002:9002"
    command: node server.js
    env_file:
      - ./Frontend/.env
    environment:
      - PORT=9002
    depends_on:
      - uvicorn