services:
  redis:
    image: "redis:latest"
    container_name: redis
  
  uvicorn:
    image: letahoangchuong/fotoverifier-backend:latest
    command: >
      uvicorn main:app --host 0.0.0.0 --port 9001
    environment:
      REDIS_URL: ${REDIS_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      TF_ENABLE_ONEDNN_OPTS: ${TF_ENABLE_ONEDNN_OPTS}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - redis

  celery:
    image: letahoangchuong/fotoverifier-backend:latest
    command: >
      celery -A tasks worker --loglevel=info -c 3
    environment:
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUD_API_KEY: ${CLOUD_API_KEY}
      CLOUD_API_SECRET: ${CLOUD_API_SECRET}
      REDIS_URL: ${REDIS_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      SERPAPI_SECRET_KEY: ${SERPAPI_SECRET_KEY}
      TF_ENABLE_ONEDNN_OPTS: ${TF_ENABLE_ONEDNN_OPTS}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - redis
      - uvicorn

  next:
    image: letahoangchuong/fotoverifier-frontend:latest
    command: npm run buildnstart
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    depends_on:
      - uvicorn