services:
  daphne:
    build:
      context: .
    container_name: daphne
    command: ["daphne", "-p", "8000", "fotoverifierbackend.asgi:application"]
    ports:
      - "8000:8000"
    environment:
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}
      - REDIS_URL=${REDIS_URL}
      - TF_ENABLE_ONEDNN_OPTS=${TF_ENABLE_ONEDNN_OPTS}
      - SERPAPI_SECRET_KEY=${SERPAPI_SECRET_KEY}
    depends_on:
      - redis
  celery:
    build:
      context: .
    container_name: celery
    command: ["celery", "-A", "fotoverifierbackend", "worker", "--loglevel=info"]
    environment:
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}
      - REDIS_URL=${REDIS_URL}
      - TF_ENABLE_ONEDNN_OPTS=${TF_ENABLE_ONEDNN_OPTS}
      - SERPAPI_SECRET_KEY=${SERPAPI_SECRET_KEY}
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
