services:
  - type: web
    plan: free
    name: fotoverifier2
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn fotoverifier2.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: SECRET_KEY
        value: your-secret-key